version: '3'
services:
  webapp:
    build:
      context: ./webapp
      args:
        - JAR_FILE=./build/libs/demo-0.0.1-SNAPSHOT.jar
    ports:
      - 8080:8080
  dependent-api:
    build:
      context: ./mock-dependencies/dependent-api
    ports:
      - 9090:9090
